# Travis auto-virtualenv isn't supported on OS X
language: generic
dist: trusty
sudo: required
matrix:
  include:
    - python: 2.7
      language: python
      python: "2.7"
      os: linux
      env: PYTHON=/usr/bin/python2.7
    - python: 3.4
      language: python
      python: "3.4"
      os: linux
      env: PYTHON=/usr/bin/python3.4
before_install:
  - source .travis.before_install.bash
install:
  - "python setup.py install"
before_script:
  - source .travis.before_script.bash
script:
  - "cd tests ; python run_tests.py"
notifications:
  email:
    - lars.pastewka@imtek.uni-freiburg.de
    - j.r.kermode@warwick.ac.uk
    - adrien.gola@kit.edu
    - richard.jana@kit.edu
    - p.patel@warwick.ac.uk
    - andreas.klemenz@iwm.fraunhofer.de
    - thomas.reichenbach@iwm.fraunhofer.de
    - gianpietro.moras@iwm.fraunhofer.de
addons:
  apt:
    packages:
    - gfortran
    - liblapack-dev
    - libopenblas-dev
    - python-numpy
    - python-scipy
